### ISSUE TITLE
License

### ISSUE THREAD

**Issue by saschpe** [marcelnicolay/pycompressor#1]
Hi, can you please add a licensing statement? Otherwise your module is essentially not redistributable.

**Comment by saschpe** [comment]
Thank you for the fast reaction. While I certainly won't question the choice of GPLv3 (it's sufficient for shipping in distros, of course), you limit the usage of your module quite narrowly. Essentially, you rule out commercial application and GPLv2 only software. For libraries / modules it's usually more appropriate to use the LGPL (check the last paragraph of your license text :-). Still, version 2 is the most compatible: https://en.wikipedia.org/wiki/GPL#Compatibility_and_multi-licensing. I hope that this is useful to you.

**Comment by marcelnicolay** [comment]
you're right... i think that LGPL is more appropriate! I'll change this
